# Generated by Django 3.0.3 on 2020-04-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.TextField()),
            ],
        ),
    ]
