# Generated by Django 3.0.3 on 2020-04-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profilee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('description', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('Image', models.ImageField(null=True, upload_to='tour_pics')),
            ],
        ),
    ]
