# Generated by Django 3.0.3 on 2020-04-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tourpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to='package_pics')),
            ],
        ),
    ]
