# Generated by Django 3.0.3 on 2020-04-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_package'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='package',
            new_name='packages_tour',
        ),
    ]
