# Generated by Django 3.0.3 on 2020-05-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200430_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('eid', models.EmailField(max_length=225)),
                ('city', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
