# Generated by Django 3.0.3 on 2020-05-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200509_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
