# Generated by Django 3.0.3 on 2020-05-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='eid',
            field=models.CharField(max_length=225),
        ),
    ]
