# Generated by Django 3.0.3 on 2020-05-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200509_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
