# Generated by Django 3.0.3 on 2020-05-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_himachal_rajasthan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('cabid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('pick', models.DateField()),
                ('drop', models.DateField()),
            ],
        ),
    ]
