# Generated by Django 3.0.3 on 2020-05-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20200510_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages_tour',
            name='desc',
            field=models.CharField(max_length=600),
        ),
    ]
