# Generated by Django 3.0.3 on 2020-05-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_uprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile'),
        ),
    ]
