# Generated by Django 3.0.3 on 2020-05-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20200516_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='pics'),
        ),
    ]
