# Generated by Django 3.0.3 on 2020-06-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descrip', models.CharField(max_length=1000)),
                ('imge', models.ImageField(upload_to='gallery_images')),
                ('pub', models.DateField()),
            ],
        ),
    ]
